<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AnalysisLevel>latest</AnalysisLevel>
    <Product>Zenith</Product>
    <Company>Zenith</Company>
    <Version>0.1.0</Version>
    <NeutralLanguage>es-ES</NeutralLanguage>
  </PropertyGroup>
</Project>
